# Site settings
title: Paul Serraino
email: pserraino99@gmail.com
description: "Paul Serraino is an Austin Texas based website developer."
baseurl: ""
url: "http://paulserraino.github.io"
excerpt_separator: ""
paginate: 5

# Build settings
markdown: kramdown
permalink: pretty
